# DELETE http://localhost:3003/api/blogs/698dd76ac7033abf6a9d6a3b
DELETE http://localhost:3003/api/blogs/698de8ff6c45e60704112c2a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2FyZG8iLCJpZCI6IjY5OGRkZDM4Yzk0ZjU3MjNiNTIwNWFjYiIsImlhdCI6MTc3MDkxMDg0MCwiZXhwIjoxNzcwOTE0NDQwfQ.wFXxEVUHTOTRx6jaSMCL15uGTIKg2wSLznz2JeXMIA0
